# Generated by Django 4.1.1 on 2022-09-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.TextField()),
                ('e', models.TextField()),
                ('d', models.TextField()),
            ],
            options={
                'db_table': 'Cryptocurrency',
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='message',
            name='payer',
        ),
    ]
