# Generated by Django 4.1.1 on 2022-09-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cryptocurrency_remove_message_payee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='value',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
